name: Run Create Components

on:
  push:
    branches:
      - main

jobs:
  run-create-components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x.x"

      - name: Install Dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./packages/ui

      - name: Run Create Components Script
        run: npm run actions:create-components
        working-directory: ./packages/ui
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Commit and Push Changes
        run: |
          run: |
            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"
            git add packages/ui/output
            git commit -m "chore(release): update components"
            git push origin HEAD:main
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
